spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: reconx-api

  jmx:
    enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  sql:
    init:
      mode: never

  cache:
    cache-names: instruments,counterparties
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5m

# Default JWT configuration
reconx:
  security:
    jwt:
      secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration-minutes: 1440
      issuer: "reconx-api"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, caches
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        reconciliation:
          duration: true

server:
  port: 8080
  servlet:
    context-path: /api
